services:
  django:
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/django.dockerfile
    volumes:
      - ./src:/usr/src/app:rw
    ports:
      - "8000:8000"
    env_file:
      - ./env/django.env
    command: "/bin/sh -c 'python3 manage.py runserver $${SERVER_IP}:$${PORT}'"
    container_name: django
