services:
  db:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    env_file:
      - ./env/db.env
    volumes:
      - db:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER:-theuserisverywise} -d ${POSTGRES_DB:-main_database}'" ]
      interval: 5s
      timeout: 3s
      retries: 6

  django:
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/django.dockerfile
    volumes:
      - ./src:/usr/src/app:rw
    ports:
      - "8000:8000"
    env_file:
      - ./env/db.env
      - ./env/django.env
    depends_on:
      db:
        condition: service_healthy
    command: "/bin/sh -c 'python3 manage.py runserver $${SERVER_IP}:$${PORT}'"
    container_name: django

volumes:
  db: